server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
logging:
  level:
    liquibase: INFO
liquibase:
  change-log: classpath:config/liquibase/master.xml
